### ISSUE TITLE
Must use different node versions for installation and execution

### ISSUE THREAD

**Issue by runderwo** [lamassu/lamassu-bitgo#17]
Hi, the latest version of lamassu-bitgo presents a conundrum.  It fails to compile native code during installation with any version of node >= 0.12, due to changes in V8 from 0.10 to 0.12, but in order to execute, it requires a minimum node of 4.x due to the usage of 'const' and other similar keywords.

**Comment by naconner** [comment]
Hey @runderwo. Good observation. A recent update to some of the BitGo module's dependencies necessitated an upgrade of node and thus lamassu-server to 2.6.0.

It isn't required at this point, although we don't have a recommended upgrade path for existing servers, and thus for this version a new server should be used with the lamassu-install script.

This is less of an issue though, as we'll be migrating to our beta, which is about to go into field testing: https://support.lamassu.is/hc/en-us/categories/115000160112-Next-Gen-Beta-
